# Generated by Django 3.1.7 on 2021-03-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_author',
            field=models.CharField(default='', max_length=50),
        ),
    ]
