# Generated by Django 3.1.7 on 2021-03-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_ordertracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertracker',
            name='order_id',
            field=models.IntegerField(default=''),
        ),
    ]
