# Generated by Django 3.1.7 on 2021-03-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210312_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_amount',
            field=models.IntegerField(default=0),
        ),
    ]
